from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
  
    path('key1/', views.Key1, name='Key1'),
    path('key2/', views.Key2, name='Key2'),
    path('key3/', views.Key3, name='Key3'),
    path('SentimentScore/', views.SentimentScore, name='SentimentScore'),
    path('WordCount/', views.WordCount, name='WordCount'),
    path('word_count/', views.word_count, name="word_count"),
    path('research/', views.research, name='research'),
    path('Sentiment_Main/', views.Sentiment_Main, name='Sentiment_Main'),
    path('sentiment_word/', views.sentiment_word, name='sentiment_word'),
    path('sentiment_date/', views.sentiment_date, name='sentiment_date'),
    path('word_count_session/', views.word_count_session, name='word_count_session'),
    path('date_search/', views.date_search, name='date_search'),
    path('Sentiment/', views.Sentiment, name='Sentiment'),
    path('sentiment_landing/', views.sentiment_landing, name='sentiment_landing'),
    path('overall_sentiment/', views.overall_sentiment, name='overall_sentiment'),
    path('sentiment_overall_ajax/', views.sentiment_overall_ajax, name='sentiment_overall_ajax'),
    path('sentiment_compare/', views.sentiment_compare, name='sentiment_compare'),
    path('sentiment_newspaper/', views.sentiment_newspaper, name='sentiment_newspaper'),
    path('sentiment_word_search/', views.sentiment_word_search, name='sentiment_word_search'),
    path('sentiment_word_search_result/', views.sentiment_word_search_result, name='sentiment_word_search_result'),
    path('sent_compare_search/', views.sent_compare_search, name='sent_compare_search'),
    path('sent_compare_search_result/', views.sent_compare_search_result, name='sent_compare_search_result'),
    path('research_sent/', views.research_sent, name='research_sent'),
    path('research_emotion_compare/', views.research_emotion_compare, name='research_emotion_compare'),
    path('research_emotion_compare_single/', views.research_emotion_compare_single, name='research_emotion_compare_single'),
    path('word_count_general_og/', views.word_count_general_og, name='word_count_general_og'),
    path('word_count_general_db/', views.word_count_general_db, name='word_count_general_db'),
    path('emotion_newspaper/', views.emotion_newspaper, name='emotion_newspaper'),
    path('emotion_compare/', views.emotion_compare, name='emotion_compare'),
    path('emotion_search_compare/', views.emotion_search_compare, name='emotion_search_compare'),
    path('emotion_search_compare_result/', views.emotion_search_compare_result, name='emotion_search_compare_result'),
    path('emotion_search_compare_single/', views.emotion_search_compare_single, name='emotion_search_compare_single'),
    path('emotion_search_compare_result_single/', views.emotion_search_compare_result_single, name='emotion_search_compare_result_single'),
    path('wc_search_compare_result/', views.wc_search_compare_result, name='wc_search_compare_result'),
    path('wc_search_compare/', views.wc_search_compare, name='wc_search_compare'),
    path('wc_search_compare_single/', views.wc_search_compare_single, name='wc_search_compare_single'),
    path('research_wc_compare/', views.research_wc_compare, name='research_wc_compare'),
    path('research_wc_compare_single/', views.research_wc_compare_single, name='research_wc_compare_single'),
    path('wc_search_compare_result_single/', views.wc_search_compare_result_single, name='wc_search_compare_result_single'),
    path('hl_search_compare_single/', views.hl_search_compare_single, name='hl_search_compare_single'),
    path('hl_search_compare_result_single/', views.hl_search_compare_result_single, name='hl_search_compare_result_single'),
    path('research_hl_compare_single/', views.research_hl_compare_single, name='research_hl_compare_single'),
    path('hl_search_compare/', views.hl_search_compare, name='hl_search_compare'),
    path('hl_search_compare_result/', views.hl_search_compare_result, name='hl_search_compare_result'),
    path('research_hl_compare/', views.research_hl_compare, name='research_hl_compare'),
    path('about/', views.about, name='about'),
]

