# Generated by Django 3.0.2 on 2020-01-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('newspaper', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=1000)),
                ('day_order', models.PositiveIntegerField()),
            ],
        ),
    ]
