# Generated by Django 3.0.2 on 2020-01-28 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='sentiment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
