# Generated by Django 3.0.2 on 2020-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0002_auto_20200128_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headline',
            field=models.CharField(max_length=1000),
        ),
    ]
