# Generated by Django 3.0.2 on 2020-01-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0004_auto_20200128_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='sentiment',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
