# Generated by Django 3.0.6 on 2020-07-24 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0006_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='superlative_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('newspaper', models.PositiveIntegerField()),
                ('news1', models.CharField(max_length=10)),
                ('news2', models.CharField(max_length=10)),
                ('word', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('sentiment', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='word_sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('word', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField()),
                ('sentiment', models.DecimalField(decimal_places=10, max_digits=12)),
                ('word_type', models.PositiveIntegerField()),
            ],
        ),
    ]
