# Generated by Django 3.0.6 on 2020-07-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0008_variance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variance_table',
            name='count',
        ),
        migrations.RemoveField(
            model_name='variance_table',
            name='newspaper',
        ),
    ]
