# Generated by Django 3.0.6 on 2020-07-29 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0009_auto_20200729_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='variance_table',
            name='variance_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variance_table',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
