# Generated by Django 3.0.6 on 2020-07-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0010_auto_20200729_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variance_table',
            name='variance_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
