# Generated by Django 3.0.6 on 2020-07-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0011_auto_20200729_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variance_table',
            name='variance_date',
        ),
    ]
