# Generated by Django 3.0.6 on 2020-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0012_remove_variance_table_variance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variance_table',
            name='variance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
