# Generated by Django 3.0.6 on 2020-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0013_variance_table_variance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='variance_table_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('news1', models.CharField(max_length=10)),
                ('news2', models.CharField(max_length=10)),
                ('sentiment', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
    ]
