# Generated by Django 3.0.6 on 2020-07-30 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0014_variance_table_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='variance_table_word',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
