# Generated by Django 3.0.6 on 2020-10-05 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0017_headlinewc'),
    ]

    operations = [
        migrations.CreateModel(
            name='cooc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_word', models.CharField(max_length=500)),
                ('co_word', models.CharField(max_length=500)),
                ('newspaper', models.PositiveIntegerField()),
                ('co_word_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='word_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('word', models.CharField(max_length=500)),
                ('newspaper', models.PositiveIntegerField()),
                ('word_count', models.PositiveIntegerField()),
            ],
        ),
    ]
