# Generated by Django 3.0.6 on 2020-10-05 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0019_auto_20201005_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_word_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('word', models.CharField(max_length=500)),
                ('nyt', models.PositiveIntegerField()),
                ('bbc', models.PositiveIntegerField()),
                ('fn', models.PositiveIntegerField()),
                ('overall', models.PositiveIntegerField()),
            ],
        ),
    ]
