# Generated by Django 3.0.6 on 2020-10-21 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0021_word_count_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='style_wc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('newspaper', models.PositiveIntegerField()),
                ('awc', models.DecimalField(decimal_places=10, max_digits=12)),
                ('ahrl', models.DecimalField(decimal_places=10, max_digits=12)),
                ('percent_quest', models.DecimalField(decimal_places=10, max_digits=12)),
                ('percent_exclam', models.DecimalField(decimal_places=10, max_digits=12)),
                ('ahwl', models.DecimalField(decimal_places=10, max_digits=12)),
                ('uw', models.DecimalField(decimal_places=10, max_digits=12)),
                ('wd', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
    ]
