# Generated by Django 3.0.6 on 2020-11-02 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0024_cooc_wc'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('word', models.CharField(max_length=500)),
                ('fear', models.PositiveIntegerField()),
                ('anger', models.PositiveIntegerField()),
                ('anticip', models.PositiveIntegerField()),
                ('trust', models.PositiveIntegerField()),
                ('surprise', models.PositiveIntegerField()),
                ('positive', models.PositiveIntegerField()),
                ('negative', models.PositiveIntegerField()),
                ('sadness', models.PositiveIntegerField()),
                ('disgust', models.PositiveIntegerField()),
                ('joy', models.PositiveIntegerField()),
            ],
        ),
    ]
