# Generated by Django 3.0.6 on 2020-11-02 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0025_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline_emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('newspaper', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(max_length=1000)),
                ('day_order', models.PositiveIntegerField()),
                ('sentiment', models.DecimalField(decimal_places=10, max_digits=12)),
                ('reading_level', models.DecimalField(decimal_places=1, max_digits=5)),
                ('headline_wc', models.PositiveIntegerField()),
                ('fear', models.PositiveIntegerField()),
                ('anger', models.PositiveIntegerField()),
                ('anticip', models.PositiveIntegerField()),
                ('trust', models.PositiveIntegerField()),
                ('surprise', models.PositiveIntegerField()),
                ('positive', models.PositiveIntegerField()),
                ('negative', models.PositiveIntegerField()),
                ('sadness', models.PositiveIntegerField()),
                ('disgust', models.PositiveIntegerField()),
                ('joy', models.PositiveIntegerField()),
            ],
        ),
    ]
