# Generated by Django 3.0.6 on 2020-11-10 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0026_headline_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion_associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('newspaper', models.PositiveIntegerField()),
                ('emotion', models.CharField(max_length=500)),
                ('word', models.CharField(max_length=500)),
                ('word_count', models.PositiveIntegerField()),
            ],
        ),
    ]
