# Generated by Django 3.0.6 on 2020-11-16 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0035_hl_tokens_emotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_words_emotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('newspaper', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=500)),
                ('fear', models.PositiveIntegerField()),
                ('anger', models.PositiveIntegerField()),
                ('anticip', models.PositiveIntegerField()),
                ('trust', models.PositiveIntegerField()),
                ('surprise', models.PositiveIntegerField()),
                ('sadness', models.PositiveIntegerField()),
                ('disgust', models.PositiveIntegerField()),
                ('joy', models.PositiveIntegerField()),
                ('fear_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anger_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anticip_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trust_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surprise_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sadness_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disgust_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('joy_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
