# Generated by Django 3.1.7 on 2021-04-08 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_scraper', '0038_html_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('newspaper', models.PositiveIntegerField()),
                ('day_order', models.PositiveIntegerField()),
                ('headline_link', models.CharField(max_length=1000)),
                ('img_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
